picture_of_the_day_d10.settings:
  type: config_object
  label: 'Picture of the Day settings'
  mapping:
    google_search:
      type: text
      label: 'Google search query template'
    trial_count:
      type: integer
      label: 'Trials count'
    empty_message:
      type: text
      label: 'Empty message'
