_core:
  default_config_hash: KQwOj3553sKrRoeRw2lrocD5DXwWP5geQMyKOrTSMUo
forum_access_roles_gids:
  anonymous: 1
  authenticated: 2
  content_editor: 3
  member: 4
  administrator: 5
  designer: 6
  content_administrator: 7
  site_administrator: 8
  judge: 9
