_core:
  default_config_hash: FHy-MQi7ulxF9vmvLJ2VXAzuZmbnH_jIkPljO2x3tq8
bootstrap_library: production
bootstrap_sidebar_position: both
bootstrap_content_offset: '0'
bootstrap_sidebar_first_width: '4'
bootstrap_sidebar_first_offset: '0'
bootstrap_sidebar_second_width: '3'
bootstrap_sidebar_second_offset: '0'
bootstrap_fluid_container: 0
bootstrap_button: 1
bootstrap_button_size: ''
bootstrap_button_outline: 0
bootstrap_navbar_toggle: navbar-toggleable-lg
bootstrap_navbar_container: 0
bootstrap_navbar_top_position: ''
bootstrap_navbar_top_color: navbar-dark
bootstrap_navbar_top_background: ''
bootstrap_navbar_position: ''
bootstrap_navbar_color: navbar-dark
bootstrap_navbar_background: bg-primary
bootstrap_messages_widget: toasts
bootstrap_radio: custom
bootstrap_checkbox: switch
bootstrap_select: custom
bootstrap_file: custom
bootstrap_system_messages: messages_light
bootstrap_table_hover: 1
bootstrap_table_style: table-striped
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: themes/custom/poetry_d10/poetry_nook_logo.png
favicon:
  use_default: 1
bootstrap_source: '0'
bootstrap_enable_color: 0
bootstrap_table_head: ''
bootstrap_container: container
bootstrap_region_clean_top_header: 0
bootstrap_region_width_top_header: 0
bootstrap_region_class_top_header: row
bootstrap_region_clean_top_header_form: 0
bootstrap_region_width_top_header_form: 0
bootstrap_region_class_top_header_form: row
bootstrap_region_clean_header: 1
bootstrap_region_width_header: 0
bootstrap_region_class_header: ''
bootstrap_region_clean_header_form: 0
bootstrap_region_width_header_form: 0
bootstrap_region_class_header_form: row
bootstrap_region_clean_primary_menu: 1
bootstrap_region_width_primary_menu: 0
bootstrap_region_class_primary_menu: ''
bootstrap_region_clean_secondary_menu: 0
bootstrap_region_width_secondary_menu: 0
bootstrap_region_class_secondary_menu: row
bootstrap_region_clean_page_top: 0
bootstrap_region_width_page_top: 0
bootstrap_region_class_page_top: row
bootstrap_region_clean_page_bottom: 0
bootstrap_region_width_page_bottom: 0
bootstrap_region_class_page_bottom: row
bootstrap_region_clean_highlighted: 1
bootstrap_region_width_highlighted: 0
bootstrap_region_class_highlighted: ''
bootstrap_region_clean_featured_top: 0
bootstrap_region_width_featured_top: 0
bootstrap_region_class_featured_top: row
bootstrap_region_clean_breadcrumb: 1
bootstrap_region_width_breadcrumb: 0
bootstrap_region_class_breadcrumb: ''
bootstrap_region_clean_content: 1
bootstrap_region_width_content: 0
bootstrap_region_class_content: ''
bootstrap_region_clean_sidebar_first: 1
bootstrap_region_width_sidebar_first: 0
bootstrap_region_class_sidebar_first: ''
bootstrap_region_clean_sidebar_second: 1
bootstrap_region_width_sidebar_second: 0
bootstrap_region_class_sidebar_second: ''
bootstrap_region_clean_featured_bottom_first: 0
bootstrap_region_width_featured_bottom_first: 0
bootstrap_region_class_featured_bottom_first: row
bootstrap_region_clean_featured_bottom_second: 0
bootstrap_region_width_featured_bottom_second: 0
bootstrap_region_class_featured_bottom_second: row
bootstrap_region_clean_featured_bottom_third: 0
bootstrap_region_width_featured_bottom_third: 0
bootstrap_region_class_featured_bottom_third: row
bootstrap_region_clean_footer_first: 0
bootstrap_region_width_footer_first: 0
bootstrap_region_class_footer_first: row
bootstrap_region_clean_footer_second: 0
bootstrap_region_width_footer_second: 0
bootstrap_region_class_footer_second: row
bootstrap_region_clean_footer_third: 0
bootstrap_region_width_footer_third: 0
bootstrap_region_class_footer_third: row
bootstrap_region_clean_footer_fourth: 0
bootstrap_region_width_footer_fourth: 0
bootstrap_region_class_footer_fourth: row
bootstrap_region_clean_footer_fifth: 0
bootstrap_region_width_footer_fifth: 0
bootstrap_region_class_footer_fifth: row
bootstrap_region_clean_none: 0
bootstrap_region_width_none: 0
bootstrap_region_class_none: row
bootstrap_sidebar_collapse: 0
bootstrap_hide_node_label: 0
bootstrap_breadcrumb_divider: ''
bootstrap_button_type: primary
bootstrap_image_fluid: 0
bootstrap_navbar_top_navbar: 0
bootstrap_navbar_top_class: ''
bootstrap_navbar_class: ''
bootstrap_navbar_offcanvas: offcanvas-collapse
bootstrap_navbar_flyout: 0
bootstrap_navbar_slide: 0
bootstrap_tabs_style: ''
bootstrap_messages_widget_toast_delay: '10000'
bootstrap_float_label: 0
bootstrap_navbar_top_affix: 0
bootstrap_navbar_affix: 0
bootstrap_sidebar_first_affix: 0
bootstrap_sidebar_second_affix: 0
bootstrap_scroll_spy: ''
bootstrap_google_fonts: ''
bootstrap_bootstrap_icons: 0
bootstrap_icons: ''
