amazon_sync_d10.settings:
  type: config_object
  label: 'Amazon Sync D10 settings'
  mapping:
    poets_limit:
      type: integer
      label: 'Poets limit'
    last_poet_id:
      type: integer
      label: 'Last processed poet NID'
    books_limit_per_author:
      type: integer
      label: 'Books limit per author'
